app.js, package.json, public/css/styles.css, views/post.ejs
=> delete post functionality on each post

.gitignore, README.md, app.js, package-lock.json, package.json
=> fixed issue6

app.js, views/home.ejs
=> Added search functionality

app.js, public/css/styles.css, views/post.ejs
- Added comment functionality.
- Added timestamps to comments.
- Sorted comments showing the recent one first.
- Added both client side and server side form validations for comments.
- Fixed the footer style so that it doesn't overlap with the comment section.
Fixes #39
=> Added comment functionality

.github/PULL_REQUEST_TEMPLATE.md
i have added PR template in .github.
=> Added .github with PR template

app.js, public/css/styles.css, views/home.ejs
- Added pagination for both the search and home page.
- Added different routes for post page to support access from different pages.
- Maintained the search query while changing pages after searching.
- Added user input to choose number of posts to display on a single page.
- Added styles for the above input.
- Fixes #55 
https://user-images.githubusercontent.com/35343652/105622954-c2d8c680-5e3b-11eb-88aa-88bebe11adac.mp4
=> Added pagination for home and search page

app.js, package-lock.json, package.json, public/css/styles.css, views/partials/footer.ejs, views/partials/header.ejs
Signed-off-by: Niveditha18 <palliniveditha@gmail.com>
Feature Request- Dark Mode
issue: #50
Manually run and colour fixes were made.
=> Added Night mode

views/home.ejs
Signed-off-by: KarunKarthik <kkarun0542@gmail.com>
Added button for compose routing.
issue: #5 
Tested and checked by adding a demo blog.
=> Added button for compose

CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md file added
issue: #17 
via VS Code Markup Preview
NA
=> CODE_OF_CONDUCT.md file added

public/css/styles.css, public/loader.js, views/partials/footer.ejs, views/partials/header.ejs
Added preloader to the site
issue: #95 
Code was tested on Chrome Developer Tool. Produced 0 warnings and 0 errors.
https://user-images.githubusercontent.com/59157988/106347530-10a66200-6274-11eb-9abc-522063ec2a03.mp4
=> Preloader added

public/css/styles.css, views/home.ejs, views/partials/header.ejs
Improved the style of the buttons on the homepage.
- Made all the buttons to have a consistent style.
- Improved the hover effect.
Fixes #90 
https://user-images.githubusercontent.com/35343652/106098405-ffb7fc80-615e-11eb-941e-a941e7b41d8d.mp4
=> Improved the style of the buttons on the homepage

public/css/styles.css, views/compose.ejs, views/home.ejs, views/post.ejs
Signed-off-by: KarunKarthik <kkarun0542@gmail.com>
Modified button styling and added animations.
issue: #112 
Manual testing was done.
https://user-images.githubusercontent.com/58992593/107112534-608db600-687e-11eb-855d-1d2fd01c5f09.mp4
=> Added style to buttons

.github/workflows/greetings.yml
Added GitHub actions to greet first-time contributors
issue: #123 
locally by contributor
=> Added github action

public/css/styles.css, views/about.ejs, views/compose.ejs, views/contact.ejs, views/home.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/post.ejs
Modified the fonts of Home page, header, footer, Post preview, Post, Compose, About page and Contact page. Also added a script to the footer to automatically update the present year beside copyright.
issue: #113 
The app was fully tested after adding the changes in the local machine by following the guidelines given in the Readme. The app worked perfectly without facing any issues.
=> style-modified all fonts

app.js, public/css/styles.css, views/partials/footer.ejs
I improved the alignment of the dark mode button and removed unnecessary code from the codebase
***Now What is mean by unnecessary code?***
The dark mode.js is defined two times in the codebase both in app.js and footer.ejs which causes an alignment issue but I fixed that
***before***
***after***
issue: #114 Align dark mode button to bottom left corner
I tested the code by running it on my localhost and also test its responsiveness and other parameters using the chrome inspect element.
=> Aligned dark mode button to bottom left corner

.github/workflows/dependabot.yml
A new file added dependabot.yml to auto-merge GitHub action. 
issue: #139 
NA
NA
=> dependabot auto merge added

public/css/styles.css, views/partials/header.ejs
Added animation to the navbar links and removed the outline of dark mode button.
issue: #110 
Manual testing.
=> style-added animation to the navbar links

public/css/styles.css, views/partials/footer.ejs
Footer is fixed to bottom of the page
issue: #162
I checked it in my local system
=> Footer positioning is fixed

public/css/styles.css, views/partials/header.ejs
Navbar is sticky at the top.
issue: #167 
Code tested In my local system.
NA
=> Sticky navbar

action.yml
=> Added GitHub action to auto merge dependency updates

models/Blog.model.js, routes/post.router.js
The bug causing by not importing a file in the index.route, which was needed.
issue: #298 
Locally on localhost
=> readmore bug fixed

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/automerge.yml
Made the required changes in ISSUES TEMPLATE and deleted automerge.yml.
issue: #305
Documentation was changed and tested on the browser.
=> Changes in ISSUES Template and deleted automerge.yml

package-lock.json, public/css/styles.css
Improved the margin under the navbar.
Issue reference: #232
=> Fixed margin under navbar

package-lock.json, public/css/styles.css
Changed the opacity so that text color doesn't get interfere by the background.
Issue reference: #234
=> Fixed the text color issue

.github/workflows/autoLabel.yaml
Added workflow for GSSOC label
issue: #237
tested on my local repo
=> Added workflow for GSSOC label

README.md
Added the  logos of tech stack 
issue: #321 
I have tested the code on tech stack branch of my repository 
=> Added tech stack logo

.github/ISSUE_TEMPLATE/feature_request.md, README.md, app.js, package-lock.json, package.json
Mongoose Warning is now removed
issue: #300
=> Mongo Error Warning Issue Solved

app.js, routes/user.router.js
Added constraints for username & password for signup
close: #163 
I have tested it in local machine
Username Check: username should be between 6 to 12 characters
Email Check:
Similar to username, email would be checked against the email regex and the error message would be shown on the screen
Password Check: password must contain a minimum of 8 letters, with at least a symbol, upper and lower case letters and a number
Please review my code & let me know if any further changes are required.
=> Added constraints for username & Password during signup

app.js, public/css/styles.css, routes/post.router.js, routes/user.router.js, views/compose.ejs, views/contact.ejs, views/home.ejs, views/logIn.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/post.ejs, views/signUp.ejs
- formatted and added comments in .ejs files
- added comments in styles.css
- restrict access to sign-up and login routes when logged in
- search bar was not working there was a small issue "homeStartingContent was not defined" resolved it
close: #360 
=> formatted and cleaned the code

.github/ISSUE_TEMPLATE/feature_request.md, README.md, app.js, public/css/styles.css, routes/post.router.js, routes/user.router.js, views/compose.ejs, views/contact.ejs, views/home.ejs, views/logIn.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/post.ejs, views/signUp.ejs
Commented and formatted the code and fix bug of authenticated user accessing the login page.
=> Commented and formatted the code

README.md
I have changed the old gif in the readme to a new gif with the present features of the website.
close: #378 
=> Update gif in readme

package-lock.json, package.json, public/css/styles.css, routes/post.router.js, views/edit.ejs, views/post.ejs
Added Edit button to update each post and author only authorization to edit the posts added.
close: #228 
Tested the app on my local machine and it worked perfectly.
https://user-images.githubusercontent.com/55927827/111736836-93c35c00-88a4-11eb-9843-11226042346d.mp4
=> Added update option on each post.

public/css/styles.css, views/home.ejs, views/partials/footer.ejs, views/partials/header.ejs
Change in home UI
#333  
Old PR: #339  #357 
Tested thoroughly in localhost
=> Improve UI

.github/PULL_REQUEST_TEMPLATE.md, app.js, models/User.model.js, public/css/styles.css, routes/user.router.js, views/signUp.ejs
Adding confirm password text box
close: #270 
=> Add confirm Password text box

package-lock.json, public/css/styles.css, views/home.ejs
=> Improved post content font-size

views/contact.ejs, views/home.ejs, views/logIn.ejs, views/partials/footer.ejs, views/signUp.ejs
The input fields in signup, login and contact pages were wide spreaded to full width and I have fixed that to be at centre spanning the width of 4,4 and 6 columns respectively. There is an unnecessary padding at the bottom of the footer and it has been removed. The "compose" button and "ask me anything" search query were getting coincided when the screen size is between 769px and 990px and i made changes such that they get displayed one below the other for this range also.
close: #393 
Tested thoroughly in localhost for responsiveness
=> Improved UI

public/css/styles.css, views/partials/header.ejs
Remove this line and add a description
close: #301 
=> login and signup button added

public/css/styles.css, views/partials/footer.ejs
Fixed the position of social media icons and button bug 
close: #391 
https://user-images.githubusercontent.com/54280252/111985855-2d07a200-8b33-11eb-914b-385a381f3100.mp4
https://user-images.githubusercontent.com/54280252/111986039-6a6c2f80-8b33-11eb-8d34-1c7d71c25108.mp4
=> Positioning of social icons and button bug fixed

views/logIn.ejs, views/signUp.ejs
improved login and signup page, decreased the width of the input fields to look better
close: #418 
Just small frontend change, tested on localhost
Signup page :
Login Page :
=> improved login and signup page

views/home.ejs
Reduce size of blog sneak-peek on home page to 1000 char
=> Reduce size of blog sneak-peek on home page

package-lock.json, package.json
Remove this line and add a description
close: #450 
=> Added multer dependency in package.json

routes/post.router.js, routes/user.router.js, views/dashboard.ejs, views/logIn.ejs, views/partials/header.ejs, views/post.ejs
Added a new route /dashboard route where users can view their profile and blogs. If the logged in user hits the author/:authorID route then he shall be redirected to his dashboard. If an unauthenticated user tries to manually hit the route by typing it on url then he will be redirected to login page.
close: #442  
Tested the functioning and responsiveness thoroughly in localhost.
The UI currently is exactly same as the UI of the route /author/:id but it shall be altered in coming days because will add new feature of setting status(private or public).   
So in other user's profile, only their public blogs will be displayed and …
=> Added /dashboard route

public/css/styles.css, views/contact.ejs
Changed the formatting of the contact-us page.
close: #420
Tested thoroughly on local machine.
=> ContactUS Formatting

routes/post.router.js
auth middleware was missing in edit post route which caused the bug
close: #486 
using the web client
=> fix(post) : Fixed edit post bug

routes/index.router.js, routes/post.router.js, views/post.ejs
The photo saving method was broken fixed
* Post.ejs template
* Compose Router
* GetPost Router
close: #485 
Using the client app
=> fix(blog-post): fixed the system for adding images to blogpost

views/home.ejs
Center aligned compose button in mobile and tablet view
close: #491 
Tablet mode : 
Mobile mode : 
Fullscreen mode :
=> center align compose button for mobile and tablet view issue #491

app.js, models/Blog.model.js, routes/index.router.js, routes/post.router.js, routes/user.router.js, views/author.ejs, views/compose.ejs, views/home.ejs
Added status field(private/public) to the blogs allows user to keep some blogs in public or private according to their wish.
This allows user to set save their blogs as draft if set to private status. Only blogs with status set as public will be visible to all users but private ones are gonna be visible for only the author.
**PS: The old blogs(posted before merging this feature) that didn't have the status field (set to either public or private) shall not be displayed. The new blogs that shall be posted with public status will be displayed publicly to everyone.**
close: #463 
Tested the functionality thoroughly in localhost. …
=> Added status field

.prettierrc, .prettierrc.json, package-lock.json, package.json, routes/index.router.js
photo var was declared twice.
close: #509
=> Fix prod bug

views/partials/header.ejs
I removed a conflicting bootstrap.min.js file
close: #492 
=> fixed mobile-nav

views/partials/header.ejs
Issue Reference: #506 
Screenshots:
Before:
After:
PS: Also improved the indentation of the file ```header.ejs``` a bit.
=> Improved the position of hamburger icon

package-lock.json, package.json, views/partials/header.ejs
ref - https://sick.codes/universal-netmask-npm-package-used-by-270000-projects-vulnerable-to-octal-input-data-server-side-request-forgery-remote-file-inclusion-local-file-inclusion-and-more-cve-2021-28918/
=> Update sub-dependencies due to security vulnerability

routes/post.router.js, views/dashboard.ejs, views/edit.ejs
Enabled the authors to edit the status and category field.
**PS: Ignore commits:  0d9cc84 & 86b761a**
close: #503 
Tested the functionality in localhost.
=> Updated /posts/:id/edit route 

routes/index.router.js, routes/post.router.js, views/dashboard.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/partials/posts.ejs
Update the dashboard UI that displays blogs with respect to their status. Also updated the user authorisation wrt private blogs.
close: #474 
Tested the functioning and responsiveness thoroughly in localhost.
=> Updated /dashboard UI

routes/index.router.js, routes/post.router.js, routes/user.router.js
use async and arrow syntax in all routes for consistency and performance sake
close: #532 
using client
=> refactor(routes): refactor routes

views/partials/footer.ejs, views/partials/header.ejs
Removed all the repeated script tags and added the latest versions of the popper and bootstrap and tested the code and all the div tags are closed properly.
close: #488 
I tested it on localhost:3000.
=> Remove repeated scripts to improve load time

models/User.model.js, public/checkPasswordMatch.js, routes/user.router.js, views/partials/footer.ejs, views/signUp.ejs
Removed confirm password from the schema and made appropriate changes
close: #513 
locally
=> Removed confirm Password from model

public/css/styles.css, views/home.ejs
Issue Reference: #517 
Earlier on hover:
Now on hover:
=> Added hover effect on filter button

views/partials/header.ejs
I have removed the bug. Now logo is appearing on all the pages.
close: #581
I have tested locally by running on my desktop.
=> Removed logo bug

README.md
Added my profile card in the maintainers section.
=> add RushanKhan1 as a Maintainer

public/css/styles.css, views/partials/header.ejs
Logo now redirect to home page
Closes: #586 
Tested locally, works as expected.
=> [UI]:Logo redirects to home

routes/index.router.js
Issue Reference: #440 
Earlier the first letter of the ```blogTitle``` was not necessarily capitalized but after adding this function , even if the user enters the title in lowercase it will make the first letter capital.
=> Added capitalize function

app.js, config/db.js, middlewares/auth.js, middlewares/mail.js, models/Blog.model.js, package-lock.json, routes/post.router.js, views/post.ejs
Added like functionality that didn't work previously. Users can now like the blogs they like.
close: #560 
Tested it on my local computer and worked fine.
https://user-images.githubusercontent.com/55927827/113558845-0448d780-961e-11eb-8cc7-068e3bba03da.mp4
=> Added like functionality.

public/css/styles.css
fixed the margin of the log-in and sign-up button
close: #500 
=> fixed the margin of the button

public/css/styles.css, views/404.ejs, views/contact.ejs, views/edit.ejs, views/home.ejs, views/partials/footer.ejs, views/partials/posts.ejs, views/post.ejs
I have removed all css from ejs files and replaced some of them with bootstrap classes, and others with different classes defined in styles.css
close: #553 
After replacing some classes with bootstrap classes, I have checked the visual appearance and it looks same to me (very minor difference in margin etc.)
=> moved inline styles from ejs files to styles.css issue#553

routes/user.router.js
Redirected the user to '/login' in user.routes.js while accessing '/autor/:id' without logged in
close: #562
Tested on local network
=> Redirecting a not logged-in user to /login while accessing other user profile

.eslintrc.json, .prettierignore, app.js, middlewares/auth.js, middlewares/mail.js, models/Blog.model.js, models/User.model.js, package-lock.json, package.json, public/checkPasswordMatch.js, public/darkMode.js, public/landBot.js, public/loader.js, public/postScript.js, routes/index.router.js, routes/post.router.js, routes/user.router.js
=> Add code linter: Eslint

models/User.model.js, routes/post.router.js, views/partials/posts.ejs, views/post.ejs
added likes counter functionality and also modified previous post liking functioonality, as it was not sufficient to implement likes counter
close: #487 
Tested on local system
https://user-images.githubusercontent.com/68139755/113750535-9210e980-9728-11eb-8cd2-3bbf8e73200b.mp4
=> added likes counter functionality

routes/user.router.js, views/author.ejs, views/dashboard.ejs
Added a feature so that users can see their liked posts as well as other authors' liked posts which are public
close: #623 
Tested locally 
https://user-images.githubusercontent.com/68139755/113822211-c624f280-979a-11eb-91b7-07caeb9dfb28.mp4
=> Show liked posts on dashboard and user profile

routes/user.router.js
I added validation code for first name and last name field while signup new user. In this field we allow only alphabet character. If user enter any other character then it will show error.
close: #600 
I run project on my local machine and test signup by provide multiple input. It is working fine
=> Validation for First and Last name

views/post.ejs
If there is only one like then show 1 like else show x likes where x is number of likes (on the post page)
close: #626 
=> issue #626 show 1 like if there is 1 like else show x likes

README.md, models/User.model.js, routes/user.router.js
1 - Adding string Status(to check whether he is Activated or not) and confirmation code in the user schema 
2 - Modified the signup function as when a new user is saved successfully in the database, he'll be marked as `Pending` instead of  direct login
3 - Then he will receive a confirmation email with a link that contains a unique encrypted confirmation code using nodemailer and jwt.
4 - The link will send a get request to the specific route with the confirmation code and if the user is already present in the database with that code, his account will be activated
5 - Then we redirect the user to the login page with a message that his account is finally activated.
NOTE : 
The Email and password of the send service must be written in the .env file like this 
`EMAIL = …
=> Email Verification Method

public/css/styles.css, views/post.ejs
I have changed the style of the like button as the other buttons.
close: #633 
=> Color co-ordination of the like button

public/darkMode.js
I changed the bottom property for dark mode toggle button
close: #634 
=> changed bottom to 0.6rem

package-lock.json, routes/user.router.js
Typos corrected in user router to load the login page.
close: #644
Tested it on my local machine and worked fine.
https://user-images.githubusercontent.com/55927827/114062119-c6191580-98b4-11eb-8a17-9635d7e9a705.mp4
=> solved issue regarding login

public/css/styles.css, public/js/showHidePassword.js, views/logIn.ejs, views/partials/footer.ejs
1. Added CSS for the eye icon in style.css file
2. Added functionality using script in login.ejs file
close: #641
=> added show/hide password

public/css/styles.css
The height of navbar...
close: #630 
Tested just by running main file in local machine after cloning.
------- Before ------
------- After -------
=> Height of navbar updated

models/User.model.js, routes/user.router.js
=> Remove email verification code

middlewares/validations/user.js, routes/user.router.js
Modularized validations used in user.js file
close: #657 
Web client
=> refactor(user validation) : validations used in user.js

models/Blog.model.js, routes/post.router.js, views/postitems/post.ejs
Number of views added that shows how many users have visited the blog.
close: #244 
Tested it on my local machine and it worked fine.
https://user-images.githubusercontent.com/55927827/114207300-dcd57000-9979-11eb-854e-1495bacbffb4.mp4
=> Number of views functionality added

public/css/styles.css
Removing the width:100% solves this
close: #670 
=> removed width from form group

public/css/styles.css
Changed border color of input boxes
close: #640
=> issue 640 fixed - Changed border colors of input boxes

views/navitems/contact.ejs
Added placeholder property to contact form
close: #565
=> issue 565 fixed - added placeholder property to contact form

public/css/styles.css, public/js/autoScrollUp.js, views/partials/footer.ejs
Added auto page scrolling button at center bottom. I have changed Jquery from min slim to min as fadeIn and fadeOut functions were not available in slim version
close: #285 
https://user-images.githubusercontent.com/68139755/114510376-3e386000-9c54-11eb-9e7d-b18ae01aaf0d.mp4
=> Scroll to top

routes/post.router.js, views/postitems/post.ejs
Only author of the comment can delete their comment
close: #issue_number
Tested Locally
https://user-images.githubusercontent.com/68139755/115106592-50333f00-9f83-11eb-847f-c199c9e64d1e.mp4
=> Delete comment restriction

views/navitems/home.ejs
Centered the page number component
close: #483 
Mobile view : 
Tablet view:
Full Screen View:
=> centered the page number component issue#483

public/css/styles.css, routes/post.router.js, views/postitems/post.ejs
Added a feature to add flags to comments and if flags are more than or equal to three, then comment will be deleted automatically. Once this PR get merged I will be making a PR to restrict deletion of comments to writer(of comment) only.
This feature can be improved more such that one person will be able to flag a comment only one time but that requires a different approach.
close: #411 
Locally
https://user-images.githubusercontent.com/68139755/115057551-d3ac4c00-9f01-11eb-82a2-c00c09500ca1.mp4
=> Flagging comments feature issue#411

public/css/styles.css
- Added a hover class. 
- Modified .back-to-top-btn class
close: #692 
=> Styled Scroll to Top Button

public/css/styles.css, views/partials/header.ejs
1. Removed classes text-info and btn-info
2. Added class btnFrame to nav buttons
3. Commented excess css for nav-link
close: #638 
=> navbar color fixed

public/css/styles.css, views/useritems/dashboard.ejs
Fixed inconsistency in font color on dashboard
close: #715 
=> fixed inconsistency in font colors on dashboard

public/css/styles.css
=> Improved position of back-to-top arrow

public/css/styles.css
=> Added z-index to back-to-top button

public/css/styles.css, views/postitems/post.ejs
made comment button similar to like button and made like button same as other buttons on website
close: #711  
Tested locally
Post comment button
On hover :
=> Fixed inconsistency in styling of like and comment buttons

.eslintignore, .eslintrc.json, .prettierrc.json, .slugignore, app.js, config/db.js, middlewares/auth.js, middlewares/mail.js, middlewares/validations/user.js, models/Blog.model.js, models/User.model.js, package.json, public/js/autoScrollUp.js, public/js/checkPasswordMatch.js, public/js/darkMode.js, public/js/landBot.js, public/js/loader.js, public/js/postScript.js, public/js/showHidePassword.js, routes/index.router.js, routes/post.router.js, routes/user.router.js
Lint the code and put assets in `.slugignore` to reduce build time.
fixes #606 and linting errors removed
=> Lint the code and put assets in `.slugignore` to reduce build time

.eslintrc.json, .github/workflows/node.js.yml
=> Setup CI issue #723

public/css/styles.css, views/useritems/read-profile.ejs
1.Added required classes to readprofile
2. added --color-danger:#ff0000
3. Added button-cancel class 
close: #716 
=> Styled save and cancel button

routes/index.router.js
Moved mailgun API to contact route, else it was giving error
close: #737 
=> fixed server issue on localhost

README.md, routes/index.router.js
Update project name in README.md and fix lint-error in global-require : issue #737
=> Update project name in README.md and fix lint-error in global-require

routes/index.router.js, routes/post.router.js, views/navitems/about.ejs, views/navitems/home.ejs, views/partials/footer.ejs, views/partials/header.ejs
Changed the name of website wherever needed
close: #744 
=> updated website name from daily journal to wordnook wherever needed

middlewares/validations/user.js, routes/index.router.js, routes/user.router.js, views/useritems/read-profile.ejs
Added validation while updating profile, so that if user enters a username which is already taken, then it will show error
close: #569 
Tested locally
https://user-images.githubusercontent.com/68139755/115908992-80e60d80-a488-11eb-8c62-90824192e107.mp4
=> added validation while updating profile

public/css/styles.css
Added hover effect on social media icons
close: #620
=> issue 620 fixed - edited hover effect on social media icons

app.js, dummy-data/testimonial.js, public/css/styles.css, routes/index.router.js, routes/testimonial.router.js, views/navitems/home.ejs, views/partials/footer.ejs, views/partials/testimonial.ejs, views/postitems/testimonial-write.ejs
Testimonial Section  added to website .
close: #342 
I have tested  it in my local system .
https://user-images.githubusercontent.com/67833077/116255182-a37d6c80-a78f-11eb-9e07-4a13d0fda982.mp4
=> Testimonial

public/css/styles.css, views/partials/footer.ejs
Added hover effect on footer links.
close: #762
=> issue #762 fixed - edited hover effect on footer links

middlewares/validations/user.js
Updated signup and update validation middleware to validate password correctly
close: #754 
Tested 
https://user-images.githubusercontent.com/68139755/116405786-aa6ab480-a84d-11eb-9403-12f9badbd5d6.mp4
=> added password validation on signup and update route

routes/user.router.js
Fixed user profile issue
close: #766 
Before:
After:
https://user-images.githubusercontent.com/68139755/116409282-519d1b00-a851-11eb-9af4-68541cfd082c.mp4
=> fixed user profile issue on signup issue#766

public/css/styles.css
=> reduced profile image size

public/css/styles.css, views/partials/testimonial.ejs
Added existing css classes
close: #770 
=> Testimonial btn styled

views/postitems/post.ejs
Rearranged anchor tag, form tag and h5 tag to fix the issue
close: #783 
Tested
=> fixed comment-flag issue #783

CONTRIBUTING.md, README.md
Added steps to lint in readme as well as in Contributing.md
close: #613 
=> Add Steps to lint in Readme

views/navitems/about.ejs, views/navitems/contact.ejs, views/partials/footer.ejs
remove margin between testimonial and footer
close: #774 
=> margin between testimonial and footer is removed 

public/css/styles.css, views/postitems/post.ejs
Added styles like other buttons to share button
close: #790 
Tested locally
on smaller screens:
=> Share button styled

middlewares/validations/user.js, views/useritems/read-profile.ejs
fixed email not updating bug and also added validation to email (So that user cannot change to a mail which is already registered)
close: #799 
Tested Locally
https://user-images.githubusercontent.com/68139755/116810387-1fe1c800-ab61-11eb-9f4e-1adf544b1c63.mp4
=> fixed email not updating bug and also added validation to email

public/css/styles.css, views/partials/testimonial.ejs
navigation button added to testimonial
close: #777 
https://user-images.githubusercontent.com/67833077/116803367-88668000-ab34-11eb-9c38-b001ac4588db.mp4
=> navigation button added to testimonial

public/css/styles.css, views/partials/footer.ejs
alignment of content in footer
close: #522 
I have tested it in my local system .
=> alignment of content in footer

public/css/styles.css
Changed profile image size unit and made it look better on small screens by increasing size
close: #815 
Full screen:
Mobile:
Tablet:
=> Changed profile image size

routes/post.router.js
Added a route to edit Blog
close: #805 
Tested locally
https://user-images.githubusercontent.com/68139755/117043925-713db300-ad2b-11eb-9f74-573e3a50fd5e.mp4
=> Added edit blog route

README.md
=> Added instructions in README for lock file version 2

public/css/styles.css, routes/user.router.js, views/useritems/dashboard.ejs
Added a button to delete the profile picture of a user
close: #801 
Tested locally
https://user-images.githubusercontent.com/68139755/117175649-b2e26280-adec-11eb-8f0b-87a760f84297.mp4
=> Added delete profile image button

views/useritems/dashboard.ejs
Added an if condition to check if the user has profile picture or not
close: #826 
Localhost
https://user-images.githubusercontent.com/68139755/117478889-56627d00-af7d-11eb-834a-50bcab9509f7.mp4
=> Show delete button only if user has profile picture

public/css/styles.css, views/navitems/home.ejs, views/partials/header.ejs, views/partials/posts.ejs
Added responsiveness to the mobile and tablet view of the website
close: #739 
1. Click F12
2.  Change the mode to mobile or tablet.
3. The website will NOT have an unnecessary margin on the left side and the content of the website will NOT look distorted.
https://user-images.githubusercontent.com/22374829/117200760-7a04b680-ae09-11eb-86b7-830d42ccce12.mp4
=> added responsiveness to the site

public/css/styles.css, views/partials/footer.ejs
social icons are enhanced 
close: #820 
https://user-images.githubusercontent.com/67833077/117541062-bd406e80-b02f-11eb-9c13-a384b6276935.mp4
=> social icons are enhanced 

public/css/styles.css, views/navitems/contact.ejs
contact form updated
close: #838 
I have tested it in my local system .
=> contact form updated

public/css/styles.css
input placeholder made responsive
close: #866 
=> input placeholder made responsive

views/navitems/home.ejs
Remove this line and add a description
close: #865 
=> Solved button positions issue

public/css/styles.css, views/navitems/home.ejs, views/partials/header.ejs
=> Added wall button on home page

public/css/styles.css
responsiveness of carousel
close: #864 
=> responsiveness of carousel

public/css/styles.css
Added media query to make buttons smaller on mobile device and also added some margin on right because of bot and scroll-to-top button
close: #863 
https://user-images.githubusercontent.com/68139755/118162239-22d09880-b43e-11eb-8ad0-d882b118b013.mp4
=> Fixed social buttons size and clickability on mobile viewport issue#863

public/css/styles.css, views/postitems/compose.ejs
compose page enhanced
close: #860
=> compose page enhanced

public/css/styles.css, views/navitems/contact.ejs
contact  page bug fixed
close: #issue_number
I have tested it i my local system 
=> contact  page bug fixed

middlewares/validations/user.js, public/css/styles.css, views/partials/testimonial.ejs
Testimonial image shape changed to round and profile picture updated for each author.
close: #786
By running on localhost. I tested the changes.
=> Testimonial profile image styles updated

public/css/styles.css, views/useritems/read-profile.ejs
profile page updated
close: #861 
I have tested it in my local system
or Video:
=> profile page enhanced

public/css/styles.css
footer updated
close: #issue_number
=> footer updated

routes/user.router.js, views/auth/signUp.ejs
=> Fix sign-up page rendering issue #889

public/css/styles.css, views/postitems/post.ejs
Added number of likes and comments in bootstrap pills and number of views in badge (customized to have primary color of website as background)
close: #712 
=> Improved blog post ui, added bootstrap badges and pills

public/css/styles.css, views/useritems/dashboard.ejs
dashboard page enhanced
close: #862 
=> dashboard page enhanced

models/Blog.model.js, models/Comment.model.js, routes/post.router.js
Created comment model and modified post router code accordingly
close: #857 
Tested locally
=> Created new comment model and modified routes accordingly

routes/user.router.js, views/useritems/dashboard.ejs
I have made another category for user dashboard named "My following Blogs"
close: #719
It was tested on my local machine
https://user-images.githubusercontent.com/61948033/118625504-b52ebe80-b7e7-11eb-8384-77a47b1c2d62.mp4
=> Included a my following Blogs category

public/css/styles.css
As each wall and piece of website has background color, I want to put background color in testimonial of home page so that it look like landing page of website.
close: #859 
Tested locally.
I have added the background color in testimonial section of home page.
You can also change the color of background according to future development in website.
=> Changed the background of testimonial

models/Comment.model.js, public/css/styles.css, public/js/commentReply.js, routes/post.router.js, views/partials/replyDialog.ejs, views/postitems/post.ejs
Added feature to reply to comments on blogs 
close: #229 
Tested locally
https://user-images.githubusercontent.com/68139755/119221497-5762e500-bb0d-11eb-93cf-36a76cc270a0.mp4
=> Added reply section to Comments

public/css/styles.css, views/testimonials/testimonial-wall.ejs
testimonial wall improved
close: #793 
I have tested it in my local sytem 
https://user-images.githubusercontent.com/67833077/119255050-41b9f200-bbd7-11eb-8ff4-078b893b44d7.mp4
=> testimonial wall improved

views/auth/signUp.ejs
added enctype in signup form, so that image can be uploaded
close: #921 
Tested locally
=> fixed image not uploading on signup issue

public/css/styles.css, views/useritems/dashboard.ejs
Added horizontal scroll for small screens
close: #909 
Tested locally
https://user-images.githubusercontent.com/68139755/119532156-3ff05a00-bda2-11eb-8484-5b6d5e3e98d2.mp4
=> fixed dashboard on mobile view #909

.env.example, app.js, middlewares/newsletter.js, models/User.model.js, package-lock.json, package.json, routes/user.router.js, views/newsletter.html, views/useritems/dashboard.ejs, views/useritems/newsletter.ejs
- Files Added:
.env example:
Added all the variable which is required by the Google API for authentication and sending mail from Alphavio's gmail account. You must copy all the values into it to .env file. Also, we can decide if we want to give these same values to all the developers, so that their setup time is reduced or we may add the generation process for those values into the documentation. For security reasons, I have not included them in the PR but dm you on discord.
middlewares/newsletter.js:
This the main newsletter file which handles majority of the newsletter work. Here Google APIs are initialised,  the message to be sent is composed dynamically, all the recipients are found and then a mail is sent to their respective emails with a blog having max views. This is sent only when …
=> Newsletter Feature

app.js, routes/newsletter.router.js, routes/user.router.js
Removed the newsletter routes from user.router.js and added it to newsletter.router.js (new-file)
Added separate function call for the newsletter routes in app.js
close: #954 
Tested Locally.
=> Added separate router for newsletter

routes/post.router.js, views/postitems/edit.ejs
Added feature to update image associated with blog
close: #949 
Tested locally
https://user-images.githubusercontent.com/68139755/120022213-b8a51f80-c009-11eb-80a7-ce9b4cec7d67.mp4
=> Added a field in edit blog form to update image in the blog

README.md
Updated the GIF in the readme file
close: #912 
=> Updated GIF in the readme file

public/css/styles.css, views/postitems/edit.ejs, views/useritems/read-profile.ejs
Made Edit blog form to look similar to other forms
more info : #957 
close: #950 
Tested
=> Edit blog form

views/testimonials/testimonial-wall.ejs
The footer for testimonial-wall was not covering the full screen in desktop as well as mobile mode. Fixed it.
close: #948
The code was tested in local environment at port 3000
Add a screenshot or demo video if appropriate-
=> fix: Handled footer in testinomials wall

views/auth/logIn.ejs, views/auth/signUp.ejs
Modified Login and signup forms to look like other forms
close: #952 
Tested Locally
=> Login signup form

public/css/styles.css, views/postitems/post.ejs
added border to comments and replies, also fixed margin on views badge
close: #977 
Tested locally
=> Added border to comments and replies

public/css/styles.css
Added a transition duration of 0.5s when hovered upon testimonial card divs.
close: #1000 
https://user-images.githubusercontent.com/78655439/121645080-6b1cbe00-cab1-11eb-9e50-f93d0217f15b.mp4
=> Added transition on testimonial cards.

public/css/styles.css, views/partials/footer.ejs
Removed the text-shadow which was there in footer text
close: #1012 
=> Removed text shadow in footer.

public/css/styles.css
Overlapping button in carousal in responsive
close: #983 
=> Update Overlapping buttons in carousel

models/Testimonial.model.js, routes/testimonial.router.js, views/testimonials/testimonial-wall.ejs
I have added a testimonial schema in models folder exported it to the testimonial-router.js .As there were some predefined
testimonials . I have contributed in such a way that new testimonial by a logged in user will be added in addition to predefined rendering of the testimonial.
close: #985 
It was tested locally.
=> Testimonial made Persistant

views/navitems/home.ejs
Added "?" in "looking for something" on homepage
close: #1033 
=> Added missing "?"

public/css/styles.css, views/navitems/contact.ejs
Made Contact-Us form UI similar to other forms.
close: #980 
Using Localhost
=> 💄style: Improve Contact-Us form UI

.dockerignore, .slugignore, Dockerfile, README.md, docker-compose.yml
I've dockerized this project. 🐬🐬
- Created an account of alphavio on the docker hub.
- I created an image for the project and pushed it to the docker hub.
- Created a docker-compose.yml file so that the setup instruction could be automated and run with just one command: `docker-compose up --build`
- Also, update the READE.md file and added setup instructions for installation of the project.
@Pranav016 I know that you asked in the PR #705 to make the docker-compose file to pull the image from Docker Hub but the thing is that if a contributor pulls our image from docker hub then when they want to make any changes then those changes will not be replicated in our image at Docker Hub. So, they won't be able to develop and debug because every time they would run `docker-compose up` then only …
=> Dockerized Wordnook 

public/css/styles.css, views/useritems/read-profile.ejs
Fixed the route redirect issue in the CANCEL button on the ```/read-profile``` page.
close: #1075 
- Through localhost:3000
https://user-images.githubusercontent.com/75828760/129015457-26353120-1148-4c11-aa7c-0bcb872de2b2.mp4
=> 🐛fixed : cancel button request in read-profile #1075

public/css/styles.css, views/testimonials/testimonial-write.ejs
Improved the Testimonial wall responsiveness.
- Fixed the ```write-testimonial``` div unresponsiveness discussed in issue #986. 
- Fixed the whole ```Testimonial wall``` UI for mobile view discussed in issue #982, adjusting the width of blockquotes.
close: #982 #986 
Through localhost.
https://user-images.githubusercontent.com/75828760/129140607-49d83239-7975-4a3d-8064-80e5f48ae740.mp4
=> 💄style : improved testimonial wall responsiveness

.env.example, .eslintrc.json, README.md, app.js, package-lock.json, package.json, routes/user.router.js
Issue- #1098 
And remove deprecated code
=> Fix and update faulty dependencies | Fix build errors
